// services/seed_data.dart (updated with more cards and rewards map)
import 'package:cloud_firestore/cloud_firestore.dart';

Future<void> seedCreditCards() async {
  final firestore = FirebaseFirestore.instance;
  final cardsRef = firestore.collection('cards');

  final cards = [
  {
    'id': '1',
    'name': 'Global Bank Platinum Card',
    'issuer': 'Global Bank',
    'annualFee': 0,
    'rewardRate': '5% on groceries',
    'signupBonus': '50,000 points',
    'benefits': ['5% airport lounge access', '1% fuel surcharge waiver', 'High approval chance'],
    'category': 'cashback',
    'rewards': {'groceries': 5, 'fuel': 1, 'dining': 2, 'travel': 3, 'online_shopping': 4, 'utilities': 1},
    'loungeAccess': 5,
    'fuelWaiver': 1,
  },
  {
    'id': '2',
    'name': 'Gold Reward Card',
    'issuer': 'ABC Bank',
    'annualFee': 95,
    'rewardRate': '3% on dining, 2% on groceries, 1% on others',
    'signupBonus': '50,000 points after \$4,000 spend',
    'benefits': ['Travel insurance', 'Purchase protection', 'Extended warranty'],
    'category': 'travel',
    'rewards': {'dining': 3, 'groceries': 2, 'travel': 5, 'online_shopping': 1, 'utilities': 1, 'fuel': 1},
    'loungeAccess': 5,
    'fuelWaiver': 1,
  },
  {
    'id': '3',
    'name': 'Shoppy Card',
    'issuer': 'XYZ Bank',
    'annualFee': 0,
    'rewardRate': '5% on single e-com, 4% on single food delivery',
    'signupBonus': '₹500 cashback',
    'benefits': ['4% on taxi app', 'Reward in cashback only'],
    'category': 'fuel',
    'rewards': {'online_shopping': 5, 'dining': 4, 'travel': 4, 'groceries': 2, 'fuel': 3, 'utilities': 1},
    'loungeAccess': 0,
    'fuelWaiver': 0,
  },
  {
    'id': '4',
    'name': 'GoldX Credit Card',
    'issuer': 'Global Bank',
    'annualFee': 150,
    'rewardRate': '3% on Amazon + Flipkart',
    'signupBonus': 'Digital Gold',
    'benefits': ['5% on Swiggy + Zomato', '5% on Uber', 'Reward in cashback & Digital Gold'],
    'category': 'highApproval',
    'rewards': {'online_shopping': 3, 'dining': 5, 'travel': 5, 'groceries': 1, 'fuel': 2, 'utilities': 1},
    'loungeAccess': 5,
    'fuelWaiver': 1,
  },
  {
    'id': '5',
    'name': 'Travel Elite Card',
    'issuer': 'Skyline Bank',
    'annualFee': 499,
    'rewardRate': '6% on flights, 4% on hotels',
    'signupBonus': 'Free flight worth ₹5,000',
    'benefits': ['Complimentary lounge access', 'Zero forex markup', 'Priority boarding'],
    'category': 'travel',
    'rewards': {'travel': 6, 'dining': 2, 'groceries': 1, 'online_shopping': 1, 'fuel': 1, 'utilities': 1},
    'loungeAccess': 8,
    'fuelWaiver': 1,
  },
  {
    'id': '6',
    'name': 'SuperSaver Card',
    'issuer': 'ABC Bank',
    'annualFee': 0,
    'rewardRate': '2% on groceries, 2% on utilities',
    'signupBonus': '₹300 cashback',
    'benefits': ['No annual fee', 'Instant approval', 'Mobile wallet compatible'],
    'category': 'cashback',
    'rewards': {'groceries': 2, 'utilities': 2, 'dining': 1, 'travel': 1, 'fuel': 1, 'online_shopping': 1},
    'loungeAccess': 0,
    'fuelWaiver': 0,
  },
  {
    'id': '7',
    'name': 'FuelMax Card',
    'issuer': 'PetroPay Bank',
    'annualFee': 299,
    'rewardRate': '5% on fuel spends',
    'signupBonus': '₹250 fuel cashback',
    'benefits': ['Fuel surcharge waiver', 'Dedicated fuel rewards', 'Instant redemption'],
    'category': 'fuel',
    'rewards': {'fuel': 5, 'groceries': 1, 'utilities': 1, 'dining': 1, 'travel': 1, 'online_shopping': 1},
    'loungeAccess': 0,
    'fuelWaiver': 5,
  },
  {
    'id': '8',
    'name': 'Jet Platinum Card',
    'issuer': 'Aero Bank',
    'annualFee': 499,
    'rewardRate': '5X points on flight bookings',
    'signupBonus': '10,000 AirMiles',
    'benefits': ['Free travel insurance', 'Priority check-in', 'Lounge access at airports'],
    'category': 'travel',
    'rewards': {'travel': 5, 'dining': 2, 'groceries': 1, 'fuel': 1, 'online_shopping': 1, 'utilities': 1},
    'loungeAccess': 6,
    'fuelWaiver': 1,
  },
  {
    'id': '9',
    'name': 'SmartBuy Card',
    'issuer': 'SmartBank',
    'annualFee': 0,
    'rewardRate': '3% on online shopping',
    'signupBonus': '₹200 cashback',
    'benefits': ['EMI conversion option', 'Zero joining fee', '1% fuel waiver'],
    'category': 'cashback',
    'rewards': {'online_shopping': 3, 'groceries': 1, 'fuel': 1, 'dining': 2, 'travel': 1, 'utilities': 1},
    'loungeAccess': 0,
    'fuelWaiver': 1,
  },
  {
    'id': '10',
    'name': 'Silver Rewards Card',
    'issuer': 'ABC Bank',
    'annualFee': 499,
    'rewardRate': '2% on dining, 1% on others',
    'signupBonus': '₹1,000 bonus points',
    'benefits': ['Low forex markup', 'Travel insurance', 'Dining discounts'],
    'category': 'rewards',
    'rewards': {'dining': 2, 'travel': 2, 'online_shopping': 1, 'groceries': 1, 'fuel': 1, 'utilities': 1},
    'loungeAccess': 3,
    'fuelWaiver': 1,
  },
  {
    'id': '11',
    'name': 'Prime Cashback Card',
    'issuer': 'XYZ Bank',
    'annualFee': 750,
    'rewardRate': '5% on Amazon, 2% on others',
    'signupBonus': '₹2,000 cashback',
    'benefits': ['Free Amazon Prime', '1% fuel surcharge waiver'],
    'category': 'cashback',
    'rewards': {'online_shopping': 5, 'groceries': 2, 'fuel': 1, 'dining': 3, 'travel': 1, 'utilities': 1},
    'loungeAccess': 2,
    'fuelWaiver': 1,
  },
  {
    'id': '12',
    'name': 'Ultimate Travel Card',
    'issuer': 'FlyHigh Bank',
    'annualFee': 999,
    'rewardRate': '10X points on flights and hotels',
    'signupBonus': '25,000 travel points',
    'benefits': ['Unlimited lounge access', 'Zero forex fee', 'Priority support'],
    'category': 'travel',
    'rewards': {'travel': 10, 'dining': 3, 'groceries': 1, 'online_shopping': 2, 'fuel': 1, 'utilities': 1},
    'loungeAccess': 10,
    'fuelWaiver': 1,
  },
  {
    'id': '13',
    'name': 'ShopMore Card',
    'issuer': 'Global Bank',
    'annualFee': 399,
    'rewardRate': '4% on Flipkart, 3% on Amazon',
    'signupBonus': '₹500 Flipkart voucher',
    'benefits': ['Fast reward redemption', 'Exclusive online discounts'],
    'category': 'cashback',
    'rewards': {'online_shopping': 4, 'dining': 2, 'groceries': 1, 'travel': 1, 'fuel': 1, 'utilities': 1},
    'loungeAccess': 1,
    'fuelWaiver': 1,
  },
  {
    'id': '14',
    'name': 'Gourmet Dining Card',
    'issuer': 'Epicure Bank',
    'annualFee': 499,
    'rewardRate': '5% on dining and food delivery',
    'signupBonus': '₹1,000 dining credits',
    'benefits': ['Complimentary meal vouchers', 'Priority restaurant reservations'],
    'category': 'dining',
    'rewards': {'dining': 5, 'travel': 2, 'online_shopping': 2, 'fuel': 1, 'utilities': 1, 'groceries': 1},
    'loungeAccess': 2,
    'fuelWaiver': 1,
  },
  {
    'id': '15',
    'name': 'Titanium Edge Card',
    'issuer': 'Metro Bank',
    'annualFee': 299,
    'rewardRate': '3% on utilities and groceries',
    'signupBonus': '₹250 cashback',
    'benefits': ['Auto bill pay rewards', '1% fuel waiver'],
    'category': 'utilities',
    'rewards': {'utilities': 3, 'groceries': 3, 'fuel': 1, 'dining': 1, 'travel': 1, 'online_shopping': 1},
    'loungeAccess': 0,
    'fuelWaiver': 1,
  },
  {
    'id': '16',
    'name': 'Student Advantage Card',
    'issuer': 'EduBank',
    'annualFee': 0,
    'rewardRate': '2% on online subscriptions',
    'signupBonus': '₹100 wallet cashback',
    'benefits': ['No annual fee', 'Instant approval', 'Student offers'],
    'category': 'student',
    'rewards': {'online_shopping': 2, 'utilities': 2, 'dining': 1, 'travel': 1, 'fuel': 0, 'groceries': 1},
    'loungeAccess': 0,
    'fuelWaiver': 0,
  },
  {
    'id': '17',
    'name': 'Platinum Lifestyle Card',
    'issuer': 'ABC Bank',
    'annualFee': 999,
    'rewardRate': '5% on lifestyle spends',
    'signupBonus': '₹3,000 lifestyle vouchers',
    'benefits': ['Concierge service', 'Luxury brand offers', 'Airport lounge access'],
    'category': 'lifestyle',
    'rewards': {'travel': 4, 'dining': 4, 'online_shopping': 3, 'groceries': 2, 'fuel': 1, 'utilities': 1},
    'loungeAccess': 8,
    'fuelWaiver': 1,
  },
  {
    'id': '18',
    'name': 'Eco Green Card',
    'issuer': 'Nature Bank',
    'annualFee': 0,
    'rewardRate': '3% cashback on EV charging, 2% on transport',
    'signupBonus': '₹500 green credits',
    'benefits': ['Paperless statements', 'Carbon offset rewards'],
    'category': 'eco',
    'rewards': {'fuel': 3, 'utilities': 2, 'travel': 2, 'dining': 1, 'groceries': 1, 'online_shopping': 1},
    'loungeAccess': 0,
    'fuelWaiver': 2,
  },
  {
    'id': '19',
    'name': 'Luxury Miles Card',
    'issuer': 'Skyline Bank',
    'annualFee': 1499,
    'rewardRate': '10X AirMiles on travel',
    'signupBonus': 'Free flight upgrade',
    'benefits': ['Airport concierge', 'Unlimited lounge access', 'Travel concierge'],
    'category': 'travel',
    'rewards': {'travel': 10, 'dining': 3, 'groceries': 1, 'online_shopping': 2, 'fuel': 1, 'utilities': 1},
    'loungeAccess': 10,
    'fuelWaiver': 1,
  },
  {
    'id': '20',
    'name': 'Everyday Saver Card',
    'issuer': 'Metro Bank',
    'annualFee': 199,
    'rewardRate': '2% on groceries, 2% on dining',
    'signupBonus': '₹500 cashback',
    'benefits': ['Fuel waiver', 'Low interest rate'],
    'category': 'cashback',
    'rewards': {'groceries': 2, 'dining': 2, 'utilities': 1, 'fuel': 1, 'travel': 1, 'online_shopping': 1},
    'loungeAccess': 1,
    'fuelWaiver': 1,
  },
  {
    'id': '21',
    'name': 'Smart Fuel Card',
    'issuer': 'PetroPay Bank',
    'annualFee': 399,
    'rewardRate': '6% cashback on fuel',
    'signupBonus': '₹600 fuel cashback',
    'benefits': ['Fuel surcharge waiver', 'Nationwide fuel network rewards'],
    'category': 'fuel',
    'rewards': {'fuel': 6, 'groceries': 1, 'utilities': 1, 'dining': 1, 'travel': 1, 'online_shopping': 1},
    'loungeAccess': 0,
    'fuelWaiver': 5,
  },
  {
    'id': '22',
    'name': 'Corporate Expense Card',
    'issuer': 'Global Bank',
    'annualFee': 0,
    'rewardRate': '2% on travel and business services',
    'signupBonus': '₹1,000 statement credit',
    'benefits': ['Expense tracking', 'Business analytics', 'Priority business support'],
    'category': 'business',
    'rewards': {'travel': 2, 'utilities': 2, 'online_shopping': 2, 'dining': 1, 'fuel': 1, 'groceries': 1},
    'loungeAccess': 3,
    'fuelWaiver': 1,
  },
  {
    'id': '23',
    'name': 'Millennial Card',
    'issuer': 'Youth Bank',
    'annualFee': 0,
    'rewardRate': '4% on OTT and subscriptions',
    'signupBonus': '₹250 cashback',
    'benefits': ['Exclusive offers on digital services', 'Mobile wallet integration'],
    'category': 'digital',
    'rewards': {'online_shopping': 4, 'dining': 3, 'utilities': 2, 'travel': 1, 'fuel': 0, 'groceries': 1},
    'loungeAccess': 0,
    'fuelWaiver': 0,
  },
  {
    'id': '24',
    'name': 'TravelGo Infinite',
    'issuer': 'Aero Bank',
    'annualFee': 1999,
    'rewardRate': '12X points on international flights',
    'signupBonus': 'Free business class ticket',
    'benefits': ['Unlimited global lounge access', 'Zero forex fee', 'Concierge service'],
    'category': 'travel',
    'rewards': {'travel': 12, 'dining': 5, 'groceries': 2, 'online_shopping': 2, 'fuel': 1, 'utilities': 1},
    'loungeAccess': 10,
    'fuelWaiver': 1,
  },
  {
    'id': '25',
    'name': 'CashPlus Card',
    'issuer': 'XYZ Bank',
    'annualFee': 499,
    'rewardRate': '5% on bill payments, 3% on groceries',
    'signupBonus': '₹750 cashback',
    'benefits': ['Automatic bill pay rewards', 'Fuel waiver'],
    'category': 'cashback',
    'rewards': {'utilities': 5, 'groceries': 3, 'fuel': 1, 'dining': 2, 'travel': 1, 'online_shopping': 2},
    'loungeAccess': 1,
    'fuelWaiver': 1,
  },
];


  for (var card in cards) {
    final existing = await cardsRef.where('name', isEqualTo: card['name']).limit(1).get();
    if (existing.docs.isEmpty) {
      await cardsRef.add(card);
    }
  }

  print('✅ Seeded credit cards successfully');
}