// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDO6npZGfN8UMfgb5GbnEsf-rAF-Hmey_I',
    appId: '1:839976882425:web:20d8b091a2d6e938d59228',
    messagingSenderId: '839976882425',
    projectId: 'ccard-5c6f9',
    authDomain: 'ccard-5c6f9.firebaseapp.com',
    storageBucket: 'ccard-5c6f9.firebasestorage.app',
    measurementId: 'G-CHPYHZ60M6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8AiYgaBveDDhP92SKfNcpqWVLuOir9LE',
    appId: '1:839976882425:android:8b5e89b113c0c22dd59228',
    messagingSenderId: '839976882425',
    projectId: 'ccard-5c6f9',
    storageBucket: 'ccard-5c6f9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzPYCaH4ynpYDmIXiMW8B-dseERGWQXzk',
    appId: '1:839976882425:ios:90603597d2c43300d59228',
    messagingSenderId: '839976882425',
    projectId: 'ccard-5c6f9',
    storageBucket: 'ccard-5c6f9.firebasestorage.app',
    iosClientId: '839976882425-hbjml4rpl6lfm546ea30agtgnm0a1pd4.apps.googleusercontent.com',
    iosBundleId: 'com.example.creditcard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzPYCaH4ynpYDmIXiMW8B-dseERGWQXzk',
    appId: '1:839976882425:ios:90603597d2c43300d59228',
    messagingSenderId: '839976882425',
    projectId: 'ccard-5c6f9',
    storageBucket: 'ccard-5c6f9.firebasestorage.app',
    iosClientId: '839976882425-hbjml4rpl6lfm546ea30agtgnm0a1pd4.apps.googleusercontent.com',
    iosBundleId: 'com.example.creditcard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDO6npZGfN8UMfgb5GbnEsf-rAF-Hmey_I',
    appId: '1:839976882425:web:ba5df1f6507ae978d59228',
    messagingSenderId: '839976882425',
    projectId: 'ccard-5c6f9',
    authDomain: 'ccard-5c6f9.firebaseapp.com',
    storageBucket: 'ccard-5c6f9.firebasestorage.app',
    measurementId: 'G-2T2Y9XZT1H',
  );
}
